[install]
# temporary disable minimumReleaseAge for update critical security issue(CVE-2026-35209)
# minimumReleaseAge = 259200
linker = "isolated"

[install.security]
scanner = "@socketsecurity/bun-security-scanner"
