[test]
root = "tests/normal"
concurrentTestGlob = "**/*"
randomize = true
retry = 1
coverage = true
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "src/api/**",
  "src/scripts/Utils/trustedTypes.ts",
]
preload = ["./tests/preload.ts"]
