import { defineConfig } from 'oxlint';

export default defineConfig({
  categories: {},
  jsPlugins: ['eslint-plugin-depend'],
  rules: {
    'no-unused-expressions': ['warn', { allowTernary: true }],
    'no-param-reassign': 'error',
    'prefer-const': 'warn',
    'no-var': 'error',
    'no-object-constructor': 'warn',
    'no-prototype-builtins': 'warn',
    'prefer-object-spread': 'error',
    'no-array-constructor': 'warn',
    'array-callback-return': 'error',
    'prefer-destructuring': 'warn',
    'prefer-template': 'warn',
    'no-eval': 'error',
    'import/no-cycle': ['error', { maxDepth: 3 }],
    'no-useless-escape': 'warn',
    'no-loop-func': 'warn',
    'prefer-rest-params': 'warn',
    'default-param-last': 'error',
    'no-new-func': 'error',
    'prefer-spread': 'warn',
    'no-use-before-define': 'error',
    'no-useless-constructor': 'warn',
    'no-dupe-class-members': 'warn',
    'max-lines': ['error', { max: 180 }],
    'oxc/no-barrel-file': 'error',
    'unicorn/no-anonymous-default-export': 'error',
    'unicorn/no-array-callback-reference': 'error',
    'unicorn/no-array-for-each': 'warn',
    'unicorn/no-array-method-this-argument': 'error',
    'unicorn/no-array-sort': 'error',
    'no-await-in-loop': 'warn',
    'no-bitwise': 'warn',
    'promise/no-callback-in-promise': 'error',
    'unicorn/no-lonely-if': 'error',
    'typescript/no-namespace': 'error',
    'oxc/no-map-spread': 'error',
    'typescript/array-type': 'error',
    'typescript/class-literal-property-style': 'error',
    'typescript/consistent-generic-constructors': 'error',
    'typescript/consistent-indexed-object-style': 'error',
    'typescript/consistent-type-assertions': 'error',
    'typescript/consistent-type-definitions': ['error', 'type'],
    'typescript/consistent-type-imports': 'error',
  },
  settings: {
    vitest: {
      typecheck: true,
    },
  },
  env: {
    builtin: true,
  },
  ignorePatterns: [
    'src/data/cart-class.js',
    'src/data/cart-oop.js',
    'vitest-example/HelloWorld.js',
    'vitest-example/HelloWorld.test.js',
    'tests/practice.bench.ts',
    'playwright-report',
  ],
  options: { typeCheck: true, typeAware: true },
});
