import { defineConfig } from 'oxlint';

export default defineConfig({
  categories: {},
  jsPlugins: ['eslint-plugin-depend', 'eslint-plugin-simple-import-sort'],
  plugins: [
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
    'promise',
    'import',
    'vitest',
  ],
  rules: {
    'no-unused-expressions': ['warn', { allowTernary: true }],
    'no-param-reassign': 'error',
    'prefer-const': 'warn',
    'no-var': 'error',
    'no-object-constructor': 'warn',
    'no-prototype-builtins': 'warn',
    'prefer-object-spread': 'error',
    'no-array-constructor': 'warn',
    'array-callback-return': 'error',
    'prefer-destructuring': 'warn',
    'prefer-template': 'warn',
    'no-eval': 'error',
    'import/no-cycle': ['error', { maxDepth: 3 }],
    'no-useless-escape': 'warn',
    'no-loop-func': 'warn',
    'prefer-rest-params': 'warn',
    'default-param-last': 'error',
    'no-new-func': 'error',
    'prefer-spread': 'warn',
    'no-use-before-define': 'error',
    'no-useless-constructor': 'warn',
    'no-dupe-class-members': 'warn',
    'max-lines': ['error', { max: 180 }],
    'oxc/no-barrel-file': 'error',
    'unicorn/no-anonymous-default-export': 'error',
    'unicorn/no-array-callback-reference': 'error',
    'unicorn/no-array-for-each': 'warn',
    'unicorn/no-array-method-this-argument': 'error',
    'unicorn/no-array-sort': 'error',
    'no-await-in-loop': 'warn',
    'no-bitwise': 'warn',
    'promise/no-callback-in-promise': 'error',
    'unicorn/no-lonely-if': 'error',
    'typescript/no-namespace': 'error',
    'oxc/no-map-spread': 'error',
    'typescript/array-type': 'error',
    'typescript/class-literal-property-style': 'error',
    'typescript/consistent-generic-constructors': 'error',
    'typescript/consistent-indexed-object-style': 'error',
    'typescript/consistent-type-assertions': 'error',
    'typescript/consistent-type-definitions': ['error', 'type'],
    'typescript/consistent-type-imports': 'error',
    'promise/avoid-new': 'error',
    'typescript/no-confusing-non-null-assertion': 'error',
    'typescript/no-dynamic-delete': 'error',
    'typescript/no-empty-interface': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-extraneous-class': 'error',
    'typescript/no-unnecessary-condition': 'error',
    'typescript/no-unsafe-assignment': 'error',
    'typescript/consistent-return': 'error',
    'typescript/consistent-type-exports': 'error',
    'typescript/dot-notation': 'error',
    'typescript/no-deprecated': 'error',
    'typescript/no-import-type-side-effects': 'error',
    'typescript/no-mixed-enums': 'error',
    'typescript/no-unnecessary-boolean-literal-compare': 'error',
    'typescript/no-unnecessary-template-expression': 'error',
    'typescript/no-unnecessary-type-arguments': 'error',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-unnecessary-type-conversion': 'error',
    'typescript/no-unnecessary-type-parameters': 'error',
    'typescript/no-unsafe-call': 'error',
    'typescript/no-unsafe-enum-comparison': 'error',
    'typescript/no-unsafe-member-access': 'error',
    'typescript/no-unsafe-return': 'error',
    'typescript/no-useless-default-assignment': 'error',
    'typescript/non-nullable-type-assertion-style': 'error',
    // 'typescript/only-throw-error': 'error',
    'typescript/prefer-find': 'error',
    'typescript/prefer-nullish-coalescing': 'error',
    'typescript/prefer-optional-chain': 'error',
    'typescript/prefer-includes': 'error',
    'typescript/prefer-readonly': 'error',
    'typescript/prefer-reduce-type-parameter': 'error',
    'typescript/prefer-regexp-exec': 'error',
    'typescript/prefer-return-this-type': 'error',
    'typescript/promise-function-async': 'error',
    'typescript/related-getter-setter-pairs': 'error',
    'typescript/require-await': 'error',
    'typescript/restrict-plus-operands': 'error',
    'typescript/return-await': ['error', 'always'],
    'typescript/strict-boolean-expressions': [
      'error',
      { allowNullableBoolean: true },
    ],
    'typescript/switch-exhaustiveness-check': 'error',
    'typescript/use-unknown-in-catch-callback-variable': 'error',
    'promise/always-return': ['warn', { ignoreLastCallback: true }],
    'promise/catch-or-return': 'error',
    'promise/no-nesting': 'error',
    'simple-import-sort/imports': 'error',
    'simple-import-sort/exports': 'error',
    'vitest/max-nested-describe': ['error', { max: 3 }],
    'vitest/valid-describe-callback': 'allow',
    'vitest/consistent-test-filename': 'error',
    // 'vitest/consistent-test-it': 'error',
    'vitest/consistent-vitest-vi': 'error',
    'vitest/no-alias-methods': 'error',
  },
  settings: {
    vitest: {
      typecheck: true,
    },
  },
  env: {
    builtin: true,
  },
  ignorePatterns: ['packages/tests/practice.bench.ts'],
  options: { typeCheck: true, typeAware: true },
});
