on: [push]
jobs:
  test:
    name: test app
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependency
        run: bun install
      - name: Build app
        run: bun run build
      - name: Install dependency for https
        run: |
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
      - name: Install certs
        run: mkcert -install
      - name: Run Bun Server
        uses: JarvusInnovations/background-action@v1
        with:
          run: bun run api
          wait-on: https://localhost:8080
      - name: Run tests
        run: bun run test:ci
  lint:
    runs-on: ubuntu-slim
    name: Lint app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependency
        run: bun install
      - name: Lint
        run: bun run lint

  format:
    runs-on: ubuntu-slim
    name: check fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependency
        run: bun install
      - name: check fmt
        run: bun run fmt --check

  audit:
    runs-on: ubuntu-slim
    name: Audit dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Audit with bun
        run: bun audit --prod --audit-level high
