name: ci
on: [push]
jobs:
  test:
    name: test app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v5
        with:
          key: the-key
          path: |
            ./node_modules
            **/*/node_modules
            **/node_modules
            ./packages/server/certs
            ~/.bun
            **/.turbo
            **/*/.turbo
            /usr/local/bin/mkcert
            ./coverage
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependency
        run: bun i --frozen-lockfile
      - name: Build app
        run: bunx turbo web#build
      - name: Install dependency for https
        run: |
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
      - name: Run Bun Server
        uses: step-security/background-action@v1
        with:
          run: bun run --cwd ./packages/server dev
          wait-on: https://localhost:8080
      - name: Run tests
        run: bun run test:coverage
